"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv
from django.utils.translation import gettext_lazy as _
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1'
]
render_host = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if render_host:
    ALLOWED_HOSTS.append(render_host)



    
CSRF_TRUSTED_ORIGINS = []
if render_host:
    #confia no link do render para evitar erros no csrf
    CSRF_TRUSTED_ORIGINS.append(f'https://{render_host}')
else:
    pass
USE_I18N = True
USE_L10N = True
LANGUAGES = [
    ('pt', _('Portuguese')),
    ('en', _('English')),
]
# Application definition

INSTALLED_APPS = [
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'django.contrib.sites',

  
    'users',       
    'atividades', 
    'cloudinary', 

    'allauth_2fa',#login co google
    'two_factor',
    'django_otp',
    'django_otp.plugins.otp_static',
    'django_otp.plugins.otp_totp',
    
   
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

SITE_ID = 1
#pagina para onde vai quem consegue fazer login
SOCIALACCOUNT_LOGIN_ON_GET = True
#deixa fazer login direto se o email ja existir
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True

#liga automaticamente a conta Google à conta local
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

#salta o formulário
SOCIALACCOUNT_AUTO_SIGNUP = True

#garante que o email é obrigatório e único
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'allauth_2fa.middleware.AllauthTwoFactorMiddleware',
]

ROOT_URLCONF = 'core.urls'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

#Garante que as sessões e cookies funcionam bem com HTTPS
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
   
        'DIRS': [os.path.join(BASE_DIR, 'core', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n', 
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
    
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Tenta ler a variável do sistema diretamente
database_url = os.environ.get('DATABASE_URL')

if database_url:
    # Configuração para o Render + Neon (PostgreSQL)
    DATABASES = {
        'default': dj_database_url.config(
            default=database_url,
            conn_max_age=600,
            ssl_require=True  #o neon exige  o ssl
        )
    }
else:
    # Caso não encontre (localmente), usa o MySQL padrão
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'protege_db',
            'USER': 'root',
            'PASSWORD': 'Marcelo123',
            'HOST': '127.0.0.1',
            'PORT': '3306',
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/


TIME_ZONE = 'Europe/Lisbon'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.StaticFilesStorage",
    },
}
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "core", "static"),
    os.path.join(BASE_DIR, "atividades", "static"),
    os.path.join(BASE_DIR, "users", "static"),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]


LOGOUT_REDIRECT_URL = 'home'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LANGUAGE_CODE = 'pt'
LANGUAGE_COOKIE_NAME = 'django_language' # Nome padrão esperado
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/atividades/home2/'

#para o login google ser compativel com mfa
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

TWO_FACTOR_PATCH_ADMIN = True

#TWO_FACTOR_QR_FACTORY = 'qrcode.image.svg.SvgPathImage'

TWO_FACTOR_TOTP_DIGITS = 6
OTP_TOTP_ISSUER = 'Protege+'

OTP_TOTP_SYNC_MODULO = 1
#conecta o google com o mfa
ACCOUNT_ADAPTER = 'allauth_2fa.adapter.OTPAdapter'




EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp-relay.brevo.com' 
EMAIL_PORT = 2525 

EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'a71fa0001@smtp-brevo.com' 
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

DEFAULT_FROM_EMAIL = 'Equipa Protege+ <marc3lo99moreira@gmail.com>'

ACCOUNT_EMAIL_SUBJECT_PREFIX = "[Protege+] " #Mete o prefixo no assunto envez do 127......
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}


#para que sempre que se feche o browser a sessao expire
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

SESSION_COOKIE_AGE = 1800 

# Garante que a sessão é guardada a cada modificação 
SESSION_SAVE_EVERY_REQUEST = True


#configs para o render ler as variaveis do cloudinary
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET')
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')